### ISSUE TITLE
Deploy not working with service account in github actions

### ISSUE THREAD

**Issue by zal1000** [angular/angularfire#3260]
### Version info

**Angular:** 14.1.0

**AngularFire:** 7.4.1

**Firebase CLI:** Latest being downloaded every time by the actions runner

### How to reproduce these conditions

**Steps to set up and reproduce**

Running the build in a github actions runner with service account exits because the CLI is not signed in

### Expected behavior

The application being built and deployed

### Actual behavior

The deploy command exits before building the app

**Comment by gavinsawyer** [comment]
This is working in @angular/fire@7.6.1 & firebase-tools@12.3.0:

1. Add an auth step to your GitHub Actions yaml file using the secret generated by `% firebase init hosting:github`; reference the output for the FIREBASE_TOKEN env variable:
```yaml
- id:   auth
  uses: google-github-actions/auth@v1
  with:
    credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROJECT_XYZ }}
    token_format: access_token
- run:  ng deploy
  env:
    FIREBASE_TOKEN: ${{ steps.auth.outputs.access_token }}
```
2. Add `gha-creds-*.json` to your .gitignore file.
3. In [IAM & Admin](https://console.cloud.google.com/iam-admin/iam), grant `Service Account Token Creator` to the GitHub Actions principal:

<img width="527" alt="Screenshot 2023-06-03 at 21 36 07" src="https://github.com/angular/angularfire/assets/6238591/fc11e906-70be-480d-8439-badb882aa9f7">

**Comment by gavinsawyer** [comment]
This is working in @angular/fire@7.6.1 & firebase-tools@12.3.0:

1. Add this auth step before your build command using the secret generated by `% firebase init hosting:github`; reference the output for the FIREBASE_TOKEN env variable:
```yaml
- id:   auth
  uses: google-github-actions/auth@v1
  with:
    credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTFOLIO_A59E2 }}
    token_format:     access_token
- run:  ng deploy
  env:
    FIREBASE_TOKEN: ${{ steps.auth.outputs.access_token }}
```
2. Add `gha-creds-*.json` to your .gitignore file.
3. In [IAM & Admin](https://console.cloud.google.com/iam-admin/iam), grant `Service Account Token Creator` to the GitHub Actions principal:

<img width="527" alt="Screenshot 2023-06-03 at 21 36 07" src="https://github.com/angular/angularfire/assets/6238591/fc11e906-70be-480d-8439-badb882aa9f7">
